# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\"I\n\x0cInferRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05input\x18\x02 \x01(\x0c\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x10\n\x08identity\x18\x04 \x01(\t\"\x1f\n\rInferResponse\x12\x0e\n\x06output\x18\x01 \x01(\t27\n\x0bGrpcService\x12(\n\x05infer\x12\r.InferRequest\x1a\x0e.InferResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')



_INFERREQUEST = DESCRIPTOR.message_types_by_name['InferRequest']
_INFERRESPONSE = DESCRIPTOR.message_types_by_name['InferResponse']
InferRequest = _reflection.GeneratedProtocolMessageType('InferRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERREQUEST,
  '__module__' : 'infer_pb2'
  # @@protoc_insertion_point(class_scope:InferRequest)
  })
_sym_db.RegisterMessage(InferRequest)

InferResponse = _reflection.GeneratedProtocolMessageType('InferResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERRESPONSE,
  '__module__' : 'infer_pb2'
  # @@protoc_insertion_point(class_scope:InferResponse)
  })
_sym_db.RegisterMessage(InferResponse)

_GRPCSERVICE = DESCRIPTOR.services_by_name['GrpcService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _INFERREQUEST._serialized_start=15
  _INFERREQUEST._serialized_end=88
  _INFERRESPONSE._serialized_start=90
  _INFERRESPONSE._serialized_end=121
  _GRPCSERVICE._serialized_start=123
  _GRPCSERVICE._serialized_end=178
# @@protoc_insertion_point(module_scope)
